---
- name: Leer contenido del archivo
  ansible.builtin.slurp:
    src: "{{ source_file }}"
  register: partidofile

- name: Copiar archivo
  ansible.builtin.copy:
    dest: "{{ dest_file }}"
    content: "{{ partidofile['content'] | b64decode }}"
    mode: "0644"

- name: Imprimir contenido del archivo partido.txt
  ansible.builtin.debug:
    msg: |

      First Name: {{ first_name }}
      Last Name: {{ last_name }}
      City: {{ city }}
      ID: {{ id }}
      Fecha: {{ lookup('pipe', 'date -u +"%Y-%m-%dT%H:%M:%SZ"') }}

- name: Obtener datos desde la API
  ansible.builtin.uri:
    url: "{{ server }}{{ endpoint }}"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
    timeout: 30
  register: result_response

- name: Extraer datos del tenista dos
  ansible.builtin.copy:
    dest: "{{ dest_file2 }}"
    mode: "0644"
    content: |
      nombre: "{{ result_response.json[0].first_name }}"
      apellido: "{{ result_response.json[0].last_name }}"
      ciudad: "{{ result_response.json[0].address.city }}"
      id: "{{ result_response.json[0].id }}"
      current_date: "{{ ansible_date_time.date }}"

- name: Imprimir contenido del archivo segundo tenista
  ansible.builtin.debug:
    msg: |
      Segundo Tenista:
        nombre: {{ result_response.json[0].first_name }}
        apellido: {{ result_response.json[0].last_name }}
        ciudad: {{ result_response.json[0].address.city }}
        id: {{ result_response.json[0].id }}
        current_date: {{ ansible_date_time.date }}
