---
- name: Leer contenido del archivo partido.txt
  ansible.builtin.set_fact:
    file_content: "{{ lookup('file', 'partido.txt') }}"

- name: Copiar archivo
  ansible.builtin.copy:
    src: partido.txt
    dest: /home/vagrant/
    owner: vagrant
    group: vagrant
    mode: "0644"

- name: Mostrar información del tenista partido.txt
  ansible.builtin.debug:
    msg: Tenista {{ first_name }} {{ last_name }} de {{ city }} con ID {{ id }}

- name: Obtener datos desde la API
  ansible.builtin.uri:
    url: "{{ server }}{{ endpoint }}"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
    timeout: 30
  register: result_response

- name: Extraer datos del tenista dos
  ansible.builtin.copy:
    dest: "{{ dest_file2 }}"
    mode: "0644"
    content: |
      nombre: "{{ result_response.json[0].first_name }}"
      apellido: "{{ result_response.json[0].last_name }}"
      ciudad: "{{ result_response.json[0].address.city }}"
      id: "{{ result_response.json[0].id }}"
      current_date: "{{ ansible_date_time.date }}"

- name: Imprimir contenido del archivo segundo tenista
  ansible.builtin.debug:
    msg: |
      Segundo Tenista:
        nombre: {{ result_response.json[0].first_name }}
        apellido: {{ result_response.json[0].last_name }}
        ciudad: {{ result_response.json[0].address.city }}
        id: {{ result_response.json[0].id }}
        current_date: {{ ansible_date_time.date }}
