---
- name: Trabajo de Practica Final (primera solucion)
  hosts: all
  become: true

  vars:
    server: https://random-data-api.com
    endpoint: /api/users/random_user?size=1
    dest_file: /home/vagrant/partido.txt
    dest_file2: /home/vagrant/segundo_tenista.txt
    first_name: Aitor
    last_name: Menta
    city: Madrid

  vars_files:
    - partido_vars.yml

  roles:
    - roles
