
#  - name: uri module demo
#    hosts: all
#    become: false
#    vars:
#      server: "https://random-data-api.com"
#      endpoint: "/api/users/random_user?size=1"
#    tasks: 
#      - name: usuarios
#        ansible.builtin.uri:
#          url: "{{server}}{{enpoint}}"
#          method: GET
#          status_code: 200
#          timeout: 30
#        register: result
#      - name: debug
#        ansible.builtin.debug:
#          var: result.json.data   
